(()=>{"use strict";const AK="dewify:browser-accounts:v1",PK="dewify:local-profile:v2",$=(s,r=document)=>r.querySelector(s),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function clean(p){p=p&&typeof p==="object"?p:{};return{name:String(p.name||"").trim().slice(0,120),email:String(p.email||"").trim().slice(0,190),business:String(p.business||"").trim().slice(0,160),phone:String(p.phone||"").trim().slice(0,40),avatar:typeof p.avatar==="string"&&p.avatar.startsWith("data:image/")?p.avatar:""}}
function label(p){return p.name||p.business||p.email||"Unnamed account"}function initials(p){const v=label(p).trim(),a=v.split(" ").filter(Boolean);return(a.length>1?a[0][0]+a[a.length-1][0]:v.slice(0,2)||"AC").toUpperCase()}function profile(){try{return clean(JSON.parse(localStorage.getItem(PK)||"{}"))}catch{return clean({})}}
function load(){try{const x=JSON.parse(localStorage.getItem(AK)||"null");if(x&&Array.isArray(x.accounts))return{accounts:x.accounts.map(a=>({id:String(a.id||Date.now()),createdAt:Number(a.createdAt)||Date.now(),...clean(a)})),activeId:x.activeId||x.accounts[0]?.id||null}}catch{}const p=profile();if(!p.name&&!p.email&&!p.business&&!p.phone&&!p.avatar)return{accounts:[],activeId:null};const a={id:"account-"+Date.now().toString(36),createdAt:Date.now(),...p},s={accounts:[a],activeId:a.id};save(s);return s}
function save(s){localStorage.setItem(AK,JSON.stringify(s))}function active(s){return s.accounts.find(a=>a.id===s.activeId)||null}function sync(s){const a=active(s),p=profile();if(a){Object.assign(a,p);save(s)}return s}function apply(s){const a=active(s);if(a)localStorage.setItem(PK,JSON.stringify(clean(a)))}
function trigger(){const e=$("#accounts-button");if(e)return e;const nav=$(".nav");if(!nav)return null;const b=document.createElement("button");b.type="button";b.id="dewify-accounts-trigger";b.className="dewify-accounts-trigger";b.setAttribute("aria-expanded","false");b.innerHTML="<span>ACCOUNTS</span><span class='dewify-accounts-count'>0</span>";const p=$("#dewify-local-profile-trigger");if(p)p.before(b);else nav.appendChild(b);return b}
function ready(){if(document.body.dataset.dewifyAccountsReady==="true")return;const tr=trigger();if(!tr)return;document.body.dataset.dewifyAccountsReady="true";let s=load();apply(s);const back=document.createElement("div");back.id="dewify-accounts-backdrop";back.className="dewify-accounts-backdrop";const panel=document.createElement("aside");panel.id="dewify-accounts-panel";panel.className="dewify-accounts-panel";panel.setAttribute("aria-hidden","true");panel.innerHTML="<div class='dewify-accounts-head'><div><p class='dewify-local-profile-kicker'>DEWIFY / BROWSER ACCOUNTS</p><h2>Switch account</h2></div><button type='button' class='dewify-accounts-close' aria-label='Close accounts'>×</button></div><div class='dewify-accounts-body'><div class='dewify-account-list'></div><div class='dewify-accounts-divider'></div><form class='dewify-accounts-form'><label>Account name<input name='name' required maxlength='120' placeholder='Your name or account'></label><label>Email<input name='email' type='email' maxlength='190' placeholder='you@example.com'></label><label>Business / brand<input name='business' maxlength='160' placeholder='Brand or store name'></label><button class='dewify-accounts-add' type='submit'>Create another account</button></form><p class='dewify-accounts-note'>Separate browser-local workspaces. They are not server identities and never hold payment secrets.</p></div>";document.body.append(back,panel);
function render(){const list=$(".dewify-account-list",panel),count=$("#dewify-accounts-trigger .dewify-accounts-count");if(count)count.textContent=s.accounts.length;if(!list)return;if(!s.accounts.length){list.innerHTML="<div style='padding:15px;border:1px dashed #2a2a2a;border-radius:12px;color:#777;font-size:11px;line-height:1.6'>No separate accounts yet. Create one below.</div>";return}list.innerHTML=s.accounts.map(a=>{const act=a.id===s.activeId,av=a.avatar?"<img src='"+a.avatar.replace(/'/g,"&#039;")+"' alt=''>":initials(a);return"<article class='dewify-account-card "+(act?"active":"")+"'><div class='dewify-account-avatar'>"+av+"</div><div class='dewify-account-copy'><strong>"+esc(label(a))+"</strong><span>"+esc(a.business||a.email||"Browser workspace")+"</span></div><button class='dewify-account-switch' type='button' data-account-id='"+esc(a.id)+"' "+(act?"disabled":"")+">"+(act?"Active":"Switch")+"</button></article>"}).join("")}
function open(){s=sync(s);render();panel.classList.add("is-open");back.classList.add("is-open");panel.setAttribute("aria-hidden","false");tr.setAttribute("aria-expanded","true")}function close(){panel.classList.remove("is-open");back.classList.remove("is-open");panel.setAttribute("aria-hidden","true");tr.setAttribute("aria-expanded","false")}
tr.addEventListener("click",()=>panel.classList.contains("is-open")?close():open());$(".dewify-accounts-close",panel).addEventListener("click",close);back.addEventListener("click",close);
$(".dewify-account-list",panel).addEventListener("click",e=>{const b=e.target.closest("[data-account-id]");if(!b||b.disabled)return;s=sync(s);s.activeId=b.dataset.accountId;save(s);apply(s);location.reload()});
$(".dewify-accounts-form",panel).addEventListener("submit",e=>{e.preventDefault();s=sync(s);const fd=new FormData(e.currentTarget),p=clean({name:fd.get("name"),email:fd.get("email"),business:fd.get("business")});if(!p.name&&!p.email&&!p.business)return;const a={id:"account-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7),createdAt:Date.now(),...p};s.accounts.push(a);s.activeId=a.id;save(s);apply(s);location.reload()});
const menu=$(".dewify-profile-dropdown-menu");if(menu){if(!menu.querySelector("[data-profile-action='accounts']")){const b=document.createElement("button");b.type="button";b.dataset.profileAction="accounts";b.innerHTML="<span>Switch account</span><small>Manage browser workspaces</small>";b.addEventListener("click",e=>{e.stopPropagation();open()});menu.appendChild(b)}if(!menu.querySelector("[data-profile-action='builder']")){const b=document.createElement("button");b.type="button";b.dataset.profileAction="builder";b.innerHTML="<span>Build a store</span><small>Open the website builder</small>";b.addEventListener("click",e=>{e.stopPropagation();location.href="builder.html"});menu.appendChild(b)}}render()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",ready,{once:true});else ready()})();