const ORDER_KEY = "dewify-orders-v1";
const DEMO_KEY = "dewify-admin-demo-v1";
const PRODUCT_DATA = [
  ["Oversized Utility Tee","Wear",899],["Minimal Crossbody Sling","Utility",749],
  ["Classic Street Hoodie","Wear",1499],["Pocket Bluetooth Speaker","Tech",1299],
  ["Everyday Tech Organizer","Utility",699],["Metal Desk Lamp","Utility",1199],
  ["Wireless Earbuds Case","Tech",499],["Everyday Cap","Wear",599]
];
const demoOrders = [
  {id:"DEWIFY-482913",created_at:"2026-09-10T14:42:00+05:30",customer_name:"Rajan Deshmukh",customer_phone:"9422843899",customer_email:"example@email.com",delivery_address:"Flat 4B, Shree Residency, Wardha Road",city:"Nagpur",state:"Maharashtra",pincode:"440015",items:[{name:"Oversized Utility Tee",price:899,qty:2,subtotal:1798},{name:"Everyday Cap",price:599,qty:1,subtotal:599}],total:2397,payment_status:"PENDING / DEMO",order_status:"NEW"},
  {id:"DEWIFY-731604",created_at:"2026-09-10T12:18:00+05:30",customer_name:"Aarav Mehta",customer_phone:"9876543210",customer_email:"aarav@example.com",delivery_address:"21 Park View Apartments",city:"Pune",state:"Maharashtra",pincode:"411001",items:[{name:"Classic Street Hoodie",price:1499,qty:1,subtotal:1499},{name:"Minimal Crossbody Sling",price:749,qty:1,subtotal:749}],total:2248,payment_status:"PENDING / DEMO",order_status:"CONFIRMED"},
  {id:"DEWIFY-295817",created_at:"2026-09-09T19:07:00+05:30",customer_name:"Mira Shah",customer_phone:"9988776655",customer_email:"mira@example.com",delivery_address:"18 Lake Road",city:"Mumbai",state:"Maharashtra",pincode:"400001",items:[{name:"Pocket Bluetooth Speaker",price:1299,qty:1,subtotal:1299}],total:1299,payment_status:"PENDING / DEMO",order_status:"PROCESSING"},
  {id:"DEWIFY-614328",created_at:"2026-09-08T16:31:00+05:30",customer_name:"Kabir Joshi",customer_phone:"9812345678",customer_email:"kabir@example.com",delivery_address:"9 Green Avenue",city:"Bengaluru",state:"Karnataka",pincode:"560001",items:[{name:"Everyday Tech Organizer",price:699,qty:1,subtotal:699},{name:"Wireless Earbuds Case",price:499,qty:2,subtotal:998}],total:1697,payment_status:"PENDING / DEMO",order_status:"SHIPPED"},
  {id:"DEWIFY-905142",created_at:"2026-09-07T11:14:00+05:30",customer_name:"Anaya Kulkarni",customer_phone:"9765432109",customer_email:"anaya@example.com",delivery_address:"33 Riverfront Towers",city:"Nashik",state:"Maharashtra",pincode:"422001",items:[{name:"Metal Desk Lamp",price:1199,qty:1,subtotal:1199}],total:1199,payment_status:"PENDING / DEMO",order_status:"DELIVERED"},
  {id:"DEWIFY-380266",created_at:"2026-09-06T09:52:00+05:30",customer_name:"Vihaan Patil",customer_phone:"9898989898",customer_email:"vihaan@example.com",delivery_address:"7 Sunrise Society",city:"Aurangabad",state:"Maharashtra",pincode:"431001",items:[{name:"Everyday Cap",price:599,qty:2,subtotal:1198}],total:1198,payment_status:"PENDING / DEMO",order_status:"CANCELLED"}
];
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const badge=s=>`<span class="badge ${String(s).toLowerCase().replace(/[^a-z]+/g,'-')}">${esc(s)}</span>`;
const supabaseEnabled=window.DEWIFY_CONFIGURED===true&&window.supabase;
const sb=supabaseEnabled?window.supabase.createClient(window.DEWIFY_CONFIG.SUPABASE_URL,window.DEWIFY_CONFIG.SUPABASE_ANON_KEY):null;
let orders=[],currentFilter="ALL",currentSearch="",selectedId=null;
let initialOrderIds=new Set();
let notificationReady=false;
function playNewOrderSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.value=880;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.45);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.5)}catch(e){}}
async function enableNotifications(){if(!('Notification' in window)){toast('Browser notifications are not supported');return}const permission=await Notification.requestPermission();notificationReady=permission==='granted';const b=document.querySelector('#enableNotifications');if(b){b.textContent=notificationReady?'Notifications enabled':'Enable notifications';b.classList.toggle('enabled',notificationReady)}if(notificationReady)toast('New-order notifications enabled')}
function notifyNewOrder(o){playNewOrderSound();toast(`NEW ORDER • ${o.id} • ${money(o.total)}`);if(notificationReady&&document.hidden){try{new Notification('DEWIFY — New order received',{body:`${o.id} • ${o.customer_name} • ${money(o.total)}`,tag:o.id})}catch(e){}}}

function demo(){return JSON.parse(JSON.stringify(demoOrders))}
function normalize(o){return {...o,customer_name:o.customer_name??o.customer?.name,customer_phone:o.customer_phone??o.customer?.phone,customer_email:o.customer_email??o.customer?.email,delivery_address:o.delivery_address??o.customer?.address,items:(o.items||[]),total:o.total??(o.items||[]).reduce((s,i)=>s+i.price*i.qty,0),payment_status:o.payment_status??o.paymentStatus??"PENDING / DEMO",order_status:o.order_status??o.orderStatus??"NEW"}}
async function loadOrders(){
 if(sb){const {data,error}=await sb.from("orders").select("*").order("created_at",{ascending:false});if(!error){orders=data.map(normalize);return}console.error(error)}
 try{const x=JSON.parse(localStorage.getItem(ORDER_KEY)||"null");orders=Array.isArray(x)&&x.length?x.map(normalize):demo();}catch{orders=demo()}
}
function saveDemo(){localStorage.setItem(DEMO_KEY,"1");localStorage.setItem(ORDER_KEY,JSON.stringify(orders))}
function fmt(o){const d=new Date(o.created_at||`${o.date}T${o.time||"00:00:00"}`);return {date:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}),time:d.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}}
function row(o){const f=fmt(o),count=o.items.reduce((n,i)=>n+Number(i.qty||0),0);return `<div class="order-row order-click" data-order="${esc(o.id)}"><div><div class="customer-name">${esc(o.customer_name)}</div><div class="order-id">${esc(o.id)}</div></div><div class="items">${count} item${count!==1?'s':''}</div><div class="date">${f.date}<small>${f.time}</small></div><div class="price">${money(o.total)}</div><div>${badge(o.payment_status.split(" ")[0])}</div><div>${badge(o.order_status)}</div></div>`}
function filtered(){const q=currentSearch.toLowerCase();return orders.filter(o=>(currentFilter==="ALL"||o.order_status===currentFilter)&&(!q||[o.id,o.customer_name,o.customer_phone,o.customer_email].some(x=>String(x).toLowerCase().includes(q)))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
function bindRows(){document.querySelectorAll('.order-click').forEach(x=>x.onclick=()=>openDrawer(x.dataset.order))}
function overview(){const active=orders.filter(o=>o.order_status!=="CANCELLED"),revenue=active.reduce((s,o)=>s+Number(o.total||0),0);document.querySelector('#view-overview').innerHTML=`<div class="stats"><div class="stat"><div class="stat-label">TOTAL ORDERS</div><div class="stat-value">${orders.length}</div><div class="stat-sub">ALL ORDERS</div></div><div class="stat"><div class="stat-label">NEW ORDERS</div><div class="stat-value">${orders.filter(o=>o.order_status==='NEW').length}</div><div class="stat-sub">NEEDS ATTENTION</div></div><div class="stat"><div class="stat-label">REVENUE</div><div class="stat-value">${money(revenue)}</div><div class="stat-sub">EXCLUDING CANCELLED</div></div><div class="stat"><div class="stat-label">AVERAGE ORDER</div><div class="stat-value">${money(active.length?Math.round(revenue/active.length):0)}</div><div class="stat-sub">ACTIVE ORDERS</div></div></div><div class="section-head"><div><h2>Recent orders</h2><p>Latest activity from the storefront.</p></div><button class="btn secondary" onclick="showView('orders')">View all</button></div><div class="panel">${orders.length?orders.slice(0,6).map(row).join(''):'<div class="empty">No orders yet.</div>'}</div>`;bindRows()}
function ordersView(){document.querySelector('#view-orders').innerHTML=`<div class="toolbar"><input id="orderSearch" class="search" placeholder="Search customer, phone, email or order ID…" value="${esc(currentSearch)}"><div class="filters">${['ALL','NEW','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED'].map(x=>`<button class="filter ${currentFilter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div></div><div class="panel">${filtered().length?`<div class="order-row head"><div>Customer</div><div>Items</div><div>Date / time</div><div>Total</div><div>Payment</div><div>Status</div></div>${filtered().map(row).join('')}`:'<div class="empty">No orders match your search.</div>'}</div>`;document.querySelector('#orderSearch').oninput=e=>{currentSearch=e.target.value;ordersView()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;ordersView()});bindRows()}
function productsView(){document.querySelector('#view-products').innerHTML=`<div class="section-head"><div><h2>Product catalog</h2><p>Catalog preview.</p></div></div><div class="products-grid">${PRODUCT_DATA.map(p=>`<div class="product-card"><div class="product-visual"></div><h3>${p[0]}</h3><div class="product-meta"><span>${p[1].toUpperCase()}</span><span>${money(p[2])}</span></div></div>`).join('')}</div>`}
function settingsView(){document.querySelector('#view-settings').innerHTML=`<div class="settings"><div class="setting-card"><h3>Cloud connection</h3><p>${supabaseEnabled?'Connected to Supabase. Orders are shared across devices and admin access is protected by Auth.':'Supabase is not configured yet. The panel is currently using local demo storage.'}</p><div class="code-line">${supabaseEnabled?'Supabase: CONNECTED':'config.js: ADD PROJECT URL + ANON KEY'}</div></div><div class="setting-card"><h3>Storage</h3><p>Production orders use the Supabase <code>orders</code> table. localStorage is retained only as a demo fallback.</p><div class="code-line">${ORDER_KEY}</div></div><div class="setting-card"><h3>New-order notifications</h3><p>When a customer places an order, this admin panel receives it through Supabase Realtime. You get an in-panel alert and sound; optional browser notifications can alert you when this tab is in the background.</p></div><div class="setting-card"><h3>Session</h3><p>Admin sign-in uses Supabase Auth. Sign out from the control below.</p><br><button class="btn secondary" id="signOut">Sign out</button></div></div>`;document.querySelector('#signOut').onclick=signOut}
const viewNames={overview:['CONTROL CENTER','Overview'],orders:['MANAGE','Orders'],products:['CATALOG','Products'],settings:['SYSTEM','Settings']};
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#view-'+v).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelector('#pageEyebrow').textContent=viewNames[v][0];document.querySelector('#pageTitle').textContent=viewNames[v][1];if(v==='overview')overview();if(v==='orders')ordersView();if(v==='products')productsView();if(v==='settings')settingsView();document.querySelector('#sidebar').classList.remove('open')}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#mobileMenu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#overlay').onclick=closeDrawer;document.querySelector('#closeDrawer').onclick=closeDrawer;
function openDrawer(id){selectedId=id;const o=orders.find(x=>x.id===id);if(!o)return;const f=fmt(o);document.querySelector('#drawerOrderId').textContent=o.id;document.querySelector('#drawerBody').innerHTML=`<div class="detail-block"><div class="detail-title">ORDER TIME</div><div style="font-size:12px">${f.date} • ${f.time}</div></div><div class="detail-block"><div class="detail-title">CUSTOMER</div><div class="detail-grid"><div class="field"><label>Name</label><div>${esc(o.customer_name)}</div></div><div class="field"><label>Phone</label><div>${esc(o.customer_phone)}</div></div><div class="field"><label>Email</label><div>${esc(o.customer_email)}</div></div></div></div><div class="detail-block"><div class="detail-title">DELIVERY ADDRESS</div><div style="font-size:12px;line-height:1.7;color:#ddd">${esc(o.delivery_address)}<br>${esc(o.city)}, ${esc(o.state)}<br>${esc(o.pincode)}</div></div><div class="detail-block"><div class="detail-title">ITEMS</div>${o.items.map(i=>`<div class="item-detail"><div><strong>${esc(i.name)} × ${i.qty}</strong><span>${money(i.price)} each</span></div><div class="item-price">${money(i.subtotal??i.price*i.qty)}</div></div>`).join('')}<div class="total-row"><span>TOTAL</span><span>${money(o.total)}</span></div></div><div class="detail-block"><div class="detail-title">PAYMENT</div>${badge(o.payment_status)}</div><div class="detail-block"><div class="detail-title">ORDER STATUS</div><div class="status-control">${['NEW','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED'].map(s=>`<button class="status-btn ${o.order_status===s?'active':''}" data-status="${s}">${s}</button>`).join('')}</div><div class="actions" style="margin-top:15px"><button class="btn" id="confirmBtn">${o.order_status==='NEW'?'Confirm order':'Set confirmed'}</button><button class="btn secondary" id="copyContact">Copy customer contact</button><button class="btn secondary" id="copyFulfillment">Copy fulfillment info</button></div></div>`;document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>changeStatus(b.dataset.status));document.querySelector('#confirmBtn').onclick=()=>changeStatus('CONFIRMED');document.querySelector('#copyContact').onclick=()=>copyContact(o);document.querySelector('#copyFulfillment').onclick=()=>copyFulfillment(o);document.querySelector('#orderDrawer').classList.add('open');document.querySelector('#overlay').classList.add('show')}
function closeDrawer(){document.querySelector('#orderDrawer').classList.remove('open');document.querySelector('#overlay').classList.remove('show');selectedId=null}
async function changeStatus(status){const o=orders.find(x=>x.id===selectedId);if(!o)return;if(sb){const {error}=await sb.from('orders').update({order_status:status}).eq('id',o.id);if(error){toast('Could not update order');return}}o.order_status=status;if(!sb)saveDemo();await loadOrders();toast(`Order marked ${status}`);openDrawer(o.id);if(document.querySelector('#view-orders').classList.contains('active'))ordersView();overview()}
async function copyContact(o){try{await navigator.clipboard.writeText(`${o.customer_name}\n${o.customer_phone}\n${o.customer_email}`);toast('Customer contact copied')}catch{toast('Copy unavailable')}}
async function copyFulfillment(o){const items=o.items.map(i=>`${i.name} × ${i.qty}`).join('\n');const text=`DEWIFY FULFILLMENT\nOrder: ${o.id}\n\nCUSTOMER\n${o.customer_name}\n${o.customer_phone}\n${o.customer_email}\n\nSHIP TO\n${o.delivery_address}\n${o.city}, ${o.state} ${o.pincode}\n\nITEMS\n${items}\n\nOrder total: ${money(o.total)}\nPayment: ${o.payment_status}`;try{await navigator.clipboard.writeText(text);toast('Fulfillment info copied')}catch{toast('Copy unavailable')}}
document.querySelector('#deleteOrder').onclick=async()=>{const o=orders.find(x=>x.id===selectedId);if(!o||!confirm(`Delete ${o.id}?`))return;if(sb){const {error}=await sb.from('orders').delete().eq('id',o.id);if(error){toast('Could not delete order');return}}else{orders=orders.filter(x=>x.id!==o.id);saveDemo()}closeDrawer();await loadOrders();toast('Order deleted');overview()}
function resetData(){if(!confirm('Reset local demo data? This does not delete cloud orders.'))return;orders=demo();saveDemo();toast('Demo data reset');showView('overview')}
document.querySelector('#resetData').onclick=resetData;
async function signOut(){if(sb)await sb.auth.signOut();location.reload()}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function boot(){
 const auth=document.querySelector('#authScreen');
 document.querySelector('#enableNotifications')?.addEventListener('click',enableNotifications);
 if('Notification' in window && Notification.permission==='granted'){notificationReady=true;const b=document.querySelector('#enableNotifications');if(b){b.textContent='Notifications enabled';b.classList.add('enabled')}}
 if(!sb){auth.hidden=true;await loadOrders();showView('overview');return}
 const {data:{session}}=await sb.auth.getSession();
 if(!session){auth.hidden=false;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#loginEmail').value,password:document.querySelector('#loginPassword').value});document.querySelector('#loginError').textContent=error?error.message:'';if(!error)location.reload()};return}
 auth.hidden=true;await loadOrders();initialOrderIds=new Set(orders.map(o=>o.id));showView('overview');
 sb.channel('dewify-orders-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},async(payload)=>{
   const incoming=payload?.new?.id; const wasKnown=incoming && initialOrderIds.has(incoming);
   await loadOrders(); const active=document.querySelector('.view.active')?.id;
   if(active==='view-orders')ordersView();else overview();
   if(payload?.eventType==='INSERT' && !wasKnown){const fresh=orders.find(o=>o.id===incoming)||normalize(payload.new);notifyNewOrder(fresh);initialOrderIds.add(incoming)}
 }).subscribe();
}
boot();
