(()=>{"use strict";
const DB_NAME="dewify-builder-files";
const enc=new TextEncoder();
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
function activeAccount(){try{const x=JSON.parse(localStorage.getItem("dewify:browser-accounts:v1")||"null");return String(x&&x.activeId||"default").replace(/[^a-zA-Z0-9_-]/g,"_")}catch{return"default"}}
function getState(){return window.DEWIFY_GET_BUILDER_EXPORT?window.DEWIFY_GET_BUILDER_EXPORT():null}
function ready(data){const s=data&&data.state;if(!s)return false;const fields=["storeName","tagline","category","customer","contactEmail","accent","logoText","fontTone","motion","speciality","currency","cta","productStyle","delivery","homeSections","country","supportPhone","terms","privacy","cookies"];return fields.every(k=>String(s.survey&&s.survey[k]||"").trim())&&!!s.templateId&&Array.isArray(s.products)&&s.products.length>0&&!!s.payments&&!!s.payments.provider&&!!String(s.domain||"").trim()}
function normalizedDomain(v){let s=String(v||"").trim().replace(/^https?:\/\//i,"").replace(/\/$/,"").toLowerCase();return s&&!s.includes(" ")&&!s.includes("/")&&s.includes(".")?s:""}
function slug(v){return String(v||"dewify-store").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"dewify-store"}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function getFile(id){return db().then(d=>new Promise((resolve,reject)=>{const r=d.transaction("files","readonly").objectStore("files").get(activeAccount()+":"+id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)}))}
async function loadZip(){if(window.JSZip)return window.JSZip;await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";s.onload=resolve;s.onerror=()=>reject(new Error("ZIP support could not be loaded."));document.head.appendChild(s)});if(!window.JSZip)throw new Error("ZIP support is unavailable.");return window.JSZip}
function downloadText(text,name){const u=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function paymentGuide(provider){const P=provider==="stripe"?"Stripe":"Razorpay",U=P.toUpperCase();return "# "+P+" payment setup\n\nNo API keys or secret credentials are required by this Dewify export.\n\n## Steps\n1. Create your products/prices in "+P+".\n2. Create a hosted Payment Link for each product.\n3. Open payment-config.js in this ZIP.\n4. Replace each PASTE_"+U+"_PAYMENT_LINK_HERE value with its public checkout URL.\n5. Upload the changed payment-config.js with the storefront.\n\n## Security\nNever put a secret key, webhook signing secret, password, or private credential in a public GitHub repository. For API checkout rather than hosted links, use a backend/serverless function that you control and keep credentials server-side.\n"}
function domainGuide(domain){return "# Domain setup\n\nTarget domain: "+domain+"\n\n## GitHub Pages\n1. Create or open the GitHub repository that will host this storefront.\n2. Upload the ZIP contents to the repository.\n3. Open Settings → Pages and enable GitHub Pages.\n4. Under Custom domain, enter "+domain+" and save.\n5. For a subdomain such as shop.example.com, create a DNS CNAME record: name = shop, target = YOUR-GITHUB-USERNAME.github.io.\n6. Wait for DNS and HTTPS provisioning, then verify the custom domain in GitHub Pages.\n\nThe ZIP also contains a CNAME file with the chosen hostname.\n\nFor a root/apex domain, follow GitHub Pages' current A/AAAA record instructions rather than creating a root CNAME.\n"}
function legalHtml(title,body,store,domain){return "<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+esc(title)+" — "+esc(store)+"</title><style>body{margin:0;background:#f4f0e7;color:#211f1a;font:16px/1.75 system-ui,sans-serif}main{max-width:860px;margin:auto;padding:56px 20px}h1{font-size:42px;line-height:1.05}.meta{color:#756f64;font-size:12px}</style></head><body><main><p class='meta'>"+esc(domain)+"</p><h1>"+esc(title)+"</h1><p>"+esc(body)+"</p><p><a href='index.html'>Back to store</a></p></main></body></html>"}
function paymentConfig(state){const provider=String(state.payments.provider||"").toUpperCase(),products={};state.products.forEach(p=>{products[p.id]="PASTE_"+provider+"_PAYMENT_LINK_HERE"});return "window.DEWIFY_PAYMENT_CONFIG = "+JSON.stringify({provider,products},null,2)+";\n"}
function paymentRuntime(){return "(function(){var cfg=window.DEWIFY_PAYMENT_CONFIG||{};document.querySelectorAll('[data-buy-product]').forEach(function(b){b.addEventListener('click',function(){var u=cfg.products&&cfg.products[b.getAttribute('data-buy-product')];if(!u||/^PASTE_/i.test(u)){alert('Add the hosted payment link in payment-config.js first.');return}location.href=u})})})();\n"}
function injectProducts(base,state){
 const provider=String(state.payments.provider==="stripe"?"Stripe":"Razorpay");
 const cards=state.products.map(p=>"<article class='dew-product'><div class='dew-thumb'>"+(p.thumbnailKey?"<img src='products/"+esc(p.id)+"/thumbnail.webp' alt='' loading='lazy'>":"DIGITAL")+"</div><div><h2>"+esc(p.title)+"</h2><p>"+esc(p.description)+"</p><strong>"+esc(p.price||"")+"</strong><button type='button' data-buy-product='"+esc(p.id)+"'>Pay with "+provider+"</button></div></article>").join("");
 const links=[["termsEnabled","terms.html","Terms & Conditions","terms"],["privacyEnabled","privacy.html","Privacy Policy","privacy"],["cookiesEnabled","cookies.html","Cookie Policy","cookies"],["cookieDisclaimerEnabled","cookie-disclaimer.html","Cookie Disclaimer","cookieDisclaimer"],["refundEnabled","refund.html","Refund / Cancellation","refund"],["disclaimerEnabled","disclaimer.html","General Disclaimer","disclaimer"]].filter(x=>state.legal[x[0]]).map(x=>"<a href='"+x[1]+"'>"+x[2]+"</a>").join(" · ");
 const section="<section class='dew-products'><style>.dew-products{position:relative;z-index:3;padding:35px 0 12px}.dew-products-grid{display:grid;gap:12px}.dew-product{display:grid;grid-template-columns:130px 1fr;gap:16px;align-items:center;padding:14px;border:1px solid rgba(128,128,128,.2);border-radius:16px;background:rgba(255,255,255,.07)}.dew-thumb{width:130px;height:130px;border-radius:12px;background:rgba(128,128,128,.12);display:grid;place-items:center;font:10px ui-monospace,monospace}.dew-thumb img{width:100%;height:100%;object-fit:cover;border-radius:12px}.dew-product h2{margin:0 0 6px}.dew-product button{margin-top:10px}@media(max-width:680px){.dew-product{grid-template-columns:1fr}.dew-thumb{width:100%;height:190px}}</style><div class='eyebrow'>YOUR DIGITAL PRODUCTS</div><div class='dew-products-grid'>"+cards+"</div><footer class='dew-footer'><style>.dew-footer{position:relative;z-index:3;padding:22px 0;color:#756f64;font-size:12px}.dew-footer a{color:inherit;margin-right:8px}</style>"+links+"<br>Domain: "+esc(normalizedDomain(state.domain))+"</footer></section>";
 return base.replace("</section></div></body></html>","</section>"+section+"</div><script src='payment-config.js'></script><script src='payment-placeholder.js'></script></body></html>");
}
async function downloadZip(){
 const data=getState(),state=data&&data.state;
 if(!ready(data)){alert("Finish every setup field, select a template, add a product, choose a payment provider, and add your domain before downloading.");return}
 const domain=normalizedDomain(state.domain);try{
  const JSZip=await loadZip(),zip=new JSZip(),base=data.html;
  zip.file("index.html",injectProducts(base,state));
  zip.file("payment-config.js",paymentConfig(state));
  zip.file("payment-placeholder.js",paymentRuntime());
  zip.file("PAYMENT-SETUP.md",paymentGuide(state.payments.provider));
  zip.file("DOMAIN-SETUP.md",domainGuide(domain));
  zip.file("README.md","# "+(state.survey.storeName||"Dewify Store")+"\n\nRead PAYMENT-SETUP.md and DOMAIN-SETUP.md first.\n\nIMPORTANT: files inside this ZIP are included for your deployment package. A public GitHub Pages repository cannot securely gate direct file URLs after payment. Use protected/server-side storage for paid downloads in a production paid-download system.\n");
  zip.file("store-data.json",JSON.stringify({store:state.survey,domain,templateId:state.templateId,paymentProvider:state.payments.provider,legal:state.legal,products:state.products.map(({id,title,description,price,fileName,fileSize})=>({id,title,description,price,fileName,fileSize}))},null,2));
  zip.file(".nojekyll","");
  zip.file("CNAME",domain+"\n");
  const legal=[["termsEnabled","terms.html","Terms & Conditions","terms"],["privacyEnabled","privacy.html","Privacy Policy","privacy"],["cookiesEnabled","cookies.html","Cookie Policy","cookies"],["cookieDisclaimerEnabled","cookie-disclaimer.html","Cookie Disclaimer","cookieDisclaimer"],["refundEnabled","refund.html","Refund / Cancellation","refund"],["disclaimerEnabled","disclaimer.html","General Disclaimer","disclaimer"]];
  for(const x of legal)if(state.legal[x[0]])zip.file(x[1],legalHtml(x[2],state.legal[x[3]]||"",state.survey.storeName,domain));
  for(const p of state.products){const f=await getFile(p.id);if(!f||!f.blob)throw new Error("Product file missing: "+p.title);const safe=String(p.fileName||f.name||"download").replace(/\\/g,"/").split("/").pop().replace(/[^a-zA-Z0-9._-]+/g,"-")||"download";zip.file("products/"+p.id+"/"+safe,f.blob);if(p.thumbnailKey){const th=await getFile(p.thumbnailKey);if(th&&th.blob)zip.file("products/"+p.id+"/thumbnail.webp",th.blob)}}
  const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=slug(state.survey.storeName)+"-store.zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);
 }catch(e){console.error(e);alert(e&&e.message||"Could not create the ZIP.")}}
window.DEWIFY_DOWNLOAD_STORE_ZIP=downloadZip;
window.DEWIFY_DOWNLOAD_TEXT=downloadText;
})();
