(() => {
"use strict";
const B=window.DEWIFY_BUILDER,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let toastTimer=0,previewUrl="";
function S(){return B.getState();}
function toast(m){const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),3500);}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>c==="&"?"&amp;":c==="<"?"&lt;":c===">"?"&gt;":c==='"'?"&quot;":"&#39;");}
function missing(){const s=S().store,m=[];if(!s.name.trim())m.push("store name");if(!s.email.trim())m.push("email");if(!s.phone.trim())m.push("phone number");if(!s.description.trim())m.push("store info");return m;}
function render(){const s=S(),t=B.findTemplate(s.template);$("#store-name").value=s.store.name||"";$("#store-email").value=s.store.email||"";$("#store-phone").value=s.store.phone||"";$("#store-location").value=s.store.location||"";$("#store-description").value=s.store.description||"";$("#store-domain").value=s.store.domain||"";$("#store-currency").value=s.store.currency||"INR";$("#cookies-enabled").checked=!!s.cookies;$("#selected-template-name").textContent=t.name;$("#selected-template-desc").textContent=t.desc;$$("[data-payment]").forEach(x=>x.classList.toggle("selected",x.dataset.payment===s.payment));$("#field-status").textContent=missing().length+" field"+(missing().length===1?"":"s")+" empty";if(!missing().length)$("#field-status").textContent="Ready";renderProducts();}
async function renderProducts(){const host=$("#product-list"),ps=S().products;if(!ps.length){host.innerHTML='<div class="empty-products">No products yet. Open the catalog and add your first product.</div>';return;}host.innerHTML=ps.map(p=>'<article class="product-card"><div class="product-thumb" data-thumb-for="'+esc(p.id)+'"><span>NO THUMBNAIL</span></div><div class="product-card-copy"><div class="product-meta"><span>'+esc(p.category)+'</span><span>'+esc(p.currency)+'</span></div><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||"No description yet.")+'</p><div class="product-bottom"><strong>'+esc(p.currency)+' '+esc(p.price)+'</strong><button class="mini-delete" type="button" data-action="remove-product" data-id="'+esc(p.id)+'">Remove</button></div></div></article>').join("");for(const p of ps){try{const b=await B.getThumb(p.thumbKey||p.id),h=$('[data-thumb-for="'+CSS.escape(p.id)+'"]');if(b&&h){h.innerHTML="";const img=document.createElement("img");img.src=URL.createObjectURL(b);img.alt="";h.appendChild(img);}}catch(e){}}}
function open(inner){const m=$("#modal");m.innerHTML='<div class="modal-backdrop" data-action="close-modal"></div>'+inner;m.classList.add("open");m.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
function close(){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl="";}const m=$("#modal");m.classList.remove("open");m.setAttribute("aria-hidden","true");m.innerHTML="";document.body.style.overflow="";}
function templates(){const ts=B.listTemplates(),cur=S().template;let cards="";for(let i=0;i<ts.length;i++){const t=ts[i];cards+='<article class="template-card"><div class="template-shot '+t.tone+'"><span class="shot-label">0'+(i+1)+' / '+esc(t.name)+'</span><strong class="shot-title">'+(t.id==="gallery"?"Product as the hero.":t.id==="signal"?"FAST. CLEAN.":t.id==="archive"?"Objects with a story.":t.id==="studio"?"Less, but sharper.":t.id==="paper"?"A quieter storefront.":"Digital. Upgraded.")+'</strong><span class="shot-line"></span><i class="shot-block"></i></div><div class="template-copy"><div><span>'+esc(t.name)+'</span><span>'+(cur===t.id?"Selected":"Theme")+'</span></div><h3>'+esc(t.name)+'</h3><p>'+esc(t.desc)+'</p><div class="template-actions"><button class="use" type="button" data-action="use-template" data-id="'+esc(t.id)+'">'+(cur===t.id?"Use this":"Choose")+'</button></div></div></article>';}open('<section class="modal-panel" role="dialog" aria-modal="true"><div class="modal-head"><div><p class="eyebrow">DEWIFY / TEMPLATES</p><h2>Pick a different look.</h2><p>Each one changes the actual exported site. The real structure is shown here.</p></div><button class="modal-close" type="button" data-action="close-modal">×</button></div><div class="modal-body"><div class="template-grid">'+cards+'</div></div></section>');}
function catalog(){open('<section class="modal-panel" role="dialog" aria-modal="true"><div class="modal-head"><div><p class="eyebrow">DEWIFY / CATALOG</p><h2>Add a product.</h2><p>Title, price, description, category, thumbnail and the hosted checkout link customers will use.</p></div><button class="modal-close" type="button" data-action="close-modal">×</button></div><div class="modal-body"><form id="catalog-form" class="catalog-layout"><div class="catalog-form"><label class="form-field"><span>Product name</span><input name="name" placeholder="Product name"></label><div class="field-grid"><label class="form-field"><span>Price</span><input name="price" inputmode="decimal" placeholder="299"></label><label class="form-field"><span>Currency</span><select name="currency"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label></div><div class="field-grid"><label class="form-field"><span>Category</span><input name="category" placeholder="Ebooks, Templates..."></label><label class="form-field"><span>Checkout link</span><input name="buyUrl" type="url" placeholder="https://rzp.io/..."></label></div><label class="form-field"><span>Description</span><textarea name="description" rows="5" placeholder="What is included?"></textarea></label><label class="form-field"><span>Thumbnail</span><input id="product-thumb" name="thumb" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><div class="modal-actions"><button class="button" type="button" data-action="close-modal">Cancel</button><button class="button button-light" type="submit">Add product <span>+</span></button></div></div><aside class="catalog-preview"><h3>Thumbnail</h3><p class="catalog-preview-note">A square image works best. It stays in this browser until you export.</p><div id="thumb-drop" class="thumbnail-drop"><span>No thumbnail selected</span></div></aside></form></div></section>');$("#catalog-form [name=currency]").value=S().store.currency||"INR";}
document.addEventListener("click",async e=>{const t=e.target.closest("[data-action], [data-payment]");if(!t)return;if(t.dataset.action==="download"){const m=missing();if(m.length)toast("Some store fields are empty: "+m.join(", ")+". Your ZIP will still be created.");$("#save-state").textContent="Exporting…";try{await window.DEWIFY_DOWNLOAD_STORE_ZIP();$("#save-state").textContent="Auto-saved";}catch(err){console.error(err);$("#save-state").textContent="Export failed";toast("The ZIP could not be created. Check the browser console.");}return;}if(t.dataset.action==="templates"){templates();return;}if(t.dataset.action==="catalog"){catalog();return;}if(t.dataset.action==="close-modal"){close();return;}if(t.dataset.action==="use-template"){B.selectTemplate(t.dataset.id);close();render();toast("Template selected.");return;}if(t.dataset.action==="remove-product"){await B.removeProduct(t.dataset.id);renderProducts();toast("Product removed.");return;}if(t.dataset.payment){B.setPayment(t.dataset.payment);render();toast("Checkout choice saved.");}});
document.addEventListener("change",e=>{if(e.target.id!=="product-thumb")return;const f=e.target.files&&e.target.files[0],d=$("#thumb-drop");if(!f){d.innerHTML="<span>No thumbnail selected</span>";return;}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(f);d.classList.add("has-image");d.innerHTML='<img src="'+previewUrl+'" alt="">';});
document.addEventListener("submit",async e=>{if(e.target.id!=="catalog-form")return;e.preventDefault();const fd=new FormData(e.target),m=[];if(!String(fd.get("name")||"").trim())m.push("product name");if(!String(fd.get("price")||"").trim())m.push("price");if(m.length)toast("Some product fields are empty: "+m.join(", ")+". Defaults will be used so you can keep going.");try{await B.addProduct({name:fd.get("name"),price:fd.get("price"),currency:fd.get("currency"),category:fd.get("category"),buyUrl:fd.get("buyUrl"),description:fd.get("description")},$("#product-thumb").files[0]||null);close();renderProducts();toast("Product added.");}catch(err){console.error(err);toast("The product could not be saved in this browser.");}});
["store-name","store-email","store-phone","store-location","store-description","store-domain","store-currency"].forEach(id=>{const el=$("#"+id),key=id.replace("store-","");el.addEventListener("input",()=>{B.updateStore(key,el.value);$("#save-state").textContent="Auto-saved";render();});el.addEventListener("change",()=>{B.updateStore(key,el.value);$("#save-state").textContent="Auto-saved";render();});});
$("#cookies-enabled").addEventListener("change",e=>{B.setCookies(e.target.checked);render();});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("#modal").classList.contains("open"))close();});
document.addEventListener("dewify:state-save-failed",()=>{toast("Browser storage is full. Export anything important before adding more files.");});
render();
})();