(()=>{"use strict";
const cfg=window.DEWIFY_CONFIG||{},product=(cfg.products||[]).find(p=>p.id==="eboox-100"),$=s=>document.querySelector(s),token=String(cfg.PADDLE_CLIENT_TOKEN||"").trim(),priceId=String(product?.priceId||"").trim(),hasDownload=Boolean(String(product?.downloadUrl||"").trim());
let paddleReady=false,checkoutOpen=false;
const deviceKey="dewify:device-id",deviceId=(()=>{try{let id=localStorage.getItem(deviceKey);if(!id){id=crypto?.randomUUID?.()||("dewify-"+Date.now()+"-"+Math.random().toString(36).slice(2));localStorage.setItem(deviceKey,id)}return id}catch(_){return"temporary-device"}})();
const storageKey="dewify:download-ready:eboox-100:"+deviceId;
const setStatus=v=>{$("#checkoutStatus")?.replaceChildren(v)},setPrice=v=>{$("#productPrice")?.replaceChildren(v)};
const setBuyState=ready=>{const b=$("#buyButton");if(!b)return;b.disabled=!ready;b.setAttribute("aria-disabled",String(!ready));b.textContent=ready?"Buy EBOOX 100 ↗":"Preparing checkout…"};
function lock(){["#downloadBook","#downloadPersistent"].forEach(s=>{const a=$(s);if(!a)return;a.removeAttribute("href");a.setAttribute("aria-disabled","true");a.setAttribute("tabindex","-1");a.dataset.ready="false";a.classList.add("is-download-locked")});$("#downloadStateLabel")?.replaceChildren("DOWNLOAD LOCKED");$("#downloadStateTitle")?.replaceChildren("Pay to unlock your download.");$("#downloadStateCopy")?.replaceChildren("Complete your purchase to unlock the EBOOX 100 ZIP download.")}
function unlock(){if(!hasDownload)return;["#downloadBook","#downloadPersistent"].forEach(s=>{const a=$(s);if(!a)return;a.href=product.downloadUrl;a.removeAttribute("aria-disabled");a.removeAttribute("tabindex");a.dataset.ready="true";a.classList.remove("is-download-locked")});$("#downloadStateLabel")?.replaceChildren("DOWNLOAD READY");$("#downloadStateTitle")?.replaceChildren("Your EBOOX 100 ZIP is ready.");$("#downloadStateCopy")?.replaceChildren("Your payment is confirmed. Your download is unlocked.")}
function remember(tx){try{localStorage.setItem(storageKey,JSON.stringify({transactionId:tx||"Completed",ready:true}))}catch(_){}}
function restore(){if(!hasDownload){lock();return}try{const s=JSON.parse(localStorage.getItem(storageKey)||"null");s?.ready?unlock():lock()}catch(_){lock()}}
async function download(url,name){const r=await fetch(url,{mode:"cors",credentials:"omit"});if(!r.ok)throw new Error("download_http_"+r.status);const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
function success(e){if(!hasDownload)return;remember(e?.data?.transaction_id||"Completed");unlock();const tx=$("#successTransaction");if(tx)tx.textContent=e?.data?.transaction_id||"Completed";$("#downloadBar")?.removeAttribute("hidden");const m=$("#successModal");m?.classList.add("is-open");m?.setAttribute("aria-hidden","false");document.body.classList.add("locked")}
async function init(){setBuyState(false);setStatus("Loading local price & secure checkout…");if(!hasDownload){setStatus("Delivery is not ready yet.");return}if(!window.Paddle){setStatus("Paddle checkout could not load. Please refresh and try again.");return}if(!token||!priceId){setStatus("Checkout setup is incomplete. Please contact support.");return}try{if(String(cfg.PADDLE_ENVIRONMENT||"production").toLowerCase()==="sandbox")Paddle.Environment.set("sandbox");Paddle.Initialize({token,eventCallback:e=>{if(e?.name==="checkout.completed"){checkoutOpen=false;success(e);return}if(e?.name==="checkout.closed")checkoutOpen=false;if(["checkout.error","checkout.payment.error","checkout.warning"].includes(e?.name)){checkoutOpen=false;setStatus("Paddle: "+(e?.detail||e?.code||"Checkout could not complete."));setBuyState(true)}}});paddleReady=true;setBuyState(true);try{const r=await Paddle.PricePreview({items:[{priceId,quantity:1}]}),line=r?.data?.details?.lineItems?.[0],local=line?.formattedTotals?.total||line?.formattedUnitTotals?.total||line?.formattedTotals?.subtotal||line?.formattedUnitTotals?.subtotal;if(local){setPrice(local);setStatus("Local price loaded. Checkout is ready.")}else setStatus("Checkout is ready. Final tax and currency are confirmed in Paddle.")}catch(_){setStatus("Checkout is ready. Final tax and currency are confirmed in Paddle.")}}catch(err){setStatus("Checkout error: "+(err?.message||"initialize_failed"))}}
$("#buyButton")?.addEventListener("click",()=>{if(!hasDownload){setStatus("This product is temporarily unavailable because its ZIP is not ready.");return}if(!paddleReady||!window.Paddle){setStatus("Checkout is still loading. Please try again in a moment.");return}if(!priceId){setStatus("Checkout setup is incomplete. Please contact support.");return}if(checkoutOpen)return;try{checkoutOpen=true;setStatus("Opening secure checkout…");Paddle.Checkout.open({items:[{priceId,quantity:1}],settings:{displayMode:"overlay",theme:"light",locale:"en"}})}catch(err){checkoutOpen=false;setStatus("Checkout error: "+(err?.message||"open_failed"))}});
["#downloadBook","#downloadPersistent"].forEach(s=>$(s)?.addEventListener("click",async e=>{e.preventDefault();const a=e.currentTarget;if(a?.dataset?.ready!=="true"||!hasDownload){setStatus("Please complete your purchase to unlock the download.");return}a.textContent="Preparing ZIP…";try{await download(product.downloadUrl,"EBOOX 100.zip");setStatus("Download started - EBOOX 100.zip")}catch(err){console.warn(err);window.open(product.downloadUrl,"_blank","noopener");setStatus("Your ZIP opened in a new tab.")}finally{a.textContent="Download EBOOX 100 ↗"}}));
$("#closeSuccess")?.addEventListener("click",()=>{$("#successModal")?.classList.remove("is-open");$("#successModal")?.setAttribute("aria-hidden","true");document.body.classList.remove("locked")});$("#successModal .scrim")?.addEventListener("click",()=>{$("#successModal")?.classList.remove("is-open");$("#successModal")?.setAttribute("aria-hidden","true");document.body.classList.remove("locked")});window.addEventListener("keydown",e=>{if(e.key==="Escape"){$("#successModal")?.classList.remove("is-open");$("#successModal")?.setAttribute("aria-hidden","true");document.body.classList.remove("locked")}});
lock();restore();window.addEventListener("load",init,{once:true});
})();