import fs from "node:fs";
import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
const read=p=>fs.readFileSync(p,"utf8");
for(const f of ["builder.html","builder.css","builder-core.js","builder-app.js","builder-export-v2.js","builder-stars.js"])assert.equal(fs.existsSync(f),true,"Missing "+f);
for(const f of ["builder-core.js","builder-app.js","builder-export-v2.js","builder-stars.js","scripts/verify_builder.mjs"]){const r=spawnSync(process.execPath,["--check",f],{encoding:"utf8"});assert.equal(r.status,0,"Syntax failure: "+f+"\n"+r.stderr);}
const h=read("builder.html"),c=read("builder.css"),core=read("builder-core.js"),app=read("builder-app.js"),exp=read("builder-export-v2.js");
for(const token of ['data-action="download"','data-action="templates"','data-action="catalog"','id="store-name"','id="store-email"','id="store-phone"','id="store-description"','id="cookies-enabled"'])assert.equal(h.includes(token),true,"Missing "+token);
for(const p of ["razorpay","stripe","custom"])assert.equal(h.includes('data-payment="'+p+'"'),true,"Missing "+p);
assert.equal(core.includes('dewify:builder:v4'),true);assert.equal(core.includes("indexedDB.open"),true);assert.equal(core.includes("async function addProduct"),true);
assert.equal(app.includes("Your ZIP will still be created"),true);assert.equal(app.includes("Defaults will be used so you can keep going."),true);assert.equal(app.includes("data-action=\"use-template\""),true);
for(const t of ["noir","paper","gallery","signal","archive","studio"])assert.equal(c.includes("."+t),true,"Missing theme "+t);
assert.equal(exp.includes('z.file("catalog.html"'),true);assert.equal(exp.includes('z.file("privacy.html"'),true);assert.equal(exp.includes('z.file("terms.html"'),true);assert.equal(exp.includes('if(s.cookies)'),true);assert.equal(exp.includes('z.file("cookie.html"'),true);assert.equal(exp.includes('z.file("cookie-policy.html"'),true);
assert.equal(exp.includes('z.file("PAYMENT-SETUP.md"'),true);assert.equal(exp.includes('z.file("CNAME"'),true);assert.equal(c.includes("@media(max-width:760px)"),true);
console.log("PASS 1 — single-screen builder, no legacy dashboard");
console.log("PASS 2 — store fields, soft warnings, autosave");
console.log("PASS 3 — catalog modal, product thumbnails, remove flow");
console.log("PASS 4 — six distinct themes with real mini glimpses");
console.log("PASS 5 — Home/Catalog/Privacy/Terms + optional Cookie pages");
console.log("PASS 6 — Razorpay/Stripe/Custom + downloadable ZIP");
console.log("PASS 7 — JavaScript syntax checks");